# Generated by Django 4.2.6 on 2025-07-11 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_monthlysalary_paid_date_position_job_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_code',
            field=models.CharField(max_length=200, verbose_name='Tax Code'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='Parent Department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Hire Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='', max_length=151, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.position', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='bonus',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bonus'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='month_year',
            field=models.DateField(verbose_name='Month and Year'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Paid'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='paid_date',
            field=models.DateField(verbose_name='Paid Date'),
        ),
        migrations.AlterField(
            model_name='monthlysalary',
            name='salary',
            field=models.IntegerField(verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='position',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='position',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Is Manager'),
        ),
        migrations.AlterField(
            model_name='position',
            name='monthly_rate',
            field=models.IntegerField(default=0, verbose_name='Monthly Rate'),
        ),
    ]
